-- +goose Up
CREATE TABLE IF NOT EXISTS orders (
    order_id BIGINT GENERATED ALWAYS AS IDENTITY,
    user_id BIGINT NOT NULL DEFAULT 0,
    number VARCHAR(50) NOT NULL UNIQUE DEFAULT '',
    status VARCHAR(20) NOT NULL DEFAULT 'NEW',
    accrual INT NOT NULL DEFAULT 0,
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(order_id),
    CONSTRAINT check_status CHECK (status IN ('NEW', 'PROCESSING', 'INVALID', 'PROCESSED'))
);

-- +goose Down
DROP TABLE IF EXISTS orders;